import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import { Inter } from '@next/font/google';
import { JobsList } from '@components';
import { Button } from 'antd';
const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  return (
    <>
      <Head>
        <title>STEMuli Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <div className="h-[78vh] bg-hero object-cover flex justify-center items-center">
          <div className="text-center">
            <p className="text-[#f0f0f0]/50 border-t border-b inline-block py-2">
              Meet the staff who want to hire you
            </p>
            <h1 className="text-5xl font-semibold leading-[50px] text-[#fff]">
              Explore <span className="text-primary">thousands</span> of <br/> jobs around you
            </h1>
            <Button size='large' type='primary' className='w-60 h-16 uppercase text-lg font-semibold'>
              Find your job
            </Button>
          </div>
        </div>
      </div>
      <main className='container mx-auto my-10 min-h-[70vh]'>
        <JobsList />
      </main>
    </>
  )
}
